
trigger: none

pool:
  name: AKS Agent

variables:
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)'

steps:

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(terraformWorkingDirectory)'
    backendServiceArm: 'Azure subscription 1(afd85edf-13c9-4faa-99be-bf7468ed2149)'
    backendAzureRmResourceGroupName: 'tfstate-rg'
    backendAzureRmStorageAccountName: 'tfstatestorage'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(terraformWorkingDirectory)'
    environmentServiceNameAzureRM: 'Azure subscription 1(afd85edf-13c9-4faa-99be-bf7468ed2149)'

- task: TerraformTaskV4@4
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(terraformWorkingDirectory)'
    environmentServiceNameAzureRM: 'Azure subscription 1(afd85edf-13c9-4faa-99be-bf7468ed2149)'

